apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: surfdash
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /surfdash
        pathType: Prefix
        backend:
          serviceName: surfdash
          servicePort: 8080
